name: Github actions demo
run-name: ${{ github.actor }} is testing out github actions
on: 
    workflow_dispatch
    
jobs:
  explore:
    runs-on: ubuntu-latest
    steps:
      - run: echo "test"
      - name: checkout code
        uses: actions/checkout@v4
      - name: list
        run: |
          ls -l ${{ github.workspace }}