name: example05
on: 
  workflow_dispatch
jobs:
  # sequnetial jobs
  Test1:
    name: test1
    runs-on: ubuntu-latest
    steps:
     - run: echo "First step"
  Test2:
    name: test2
    runs-on: ubuntu-latest
    needs: Test1
    steps:
      - run: echo "second step"
  Test3:
    name: test3
    runs-on: ubuntu-latest
    needs: Test1
    steps:
      - run: echo "third steps"
  
  Test4: 
    name: test4
    runs-on: ubuntu-latest
    needs: ["Test2","Test3"]
    steps:
      - run: echo "test4"

 