name: example04
on:
    workflow_dispatch
jobs:
    #parallel jobs
    Test1:
      runs-on: ubuntu-latest
      steps:
        - run: echo "The job was automatically triggered by ${{ github.event_name }} event"
    Test2:
      runs-on: ubuntu-latest
      steps:
        - run: echo "The job was automatically triggered by ${{ github.event_name }}"
    Test3:
      runs-on: ubuntu-latest
      steps:
        - run: echo "The job was automatilly triggered by ${{github.event_name}}"